[build]
  command = "npm run build"
  functions = "netlify/functions/"
  publish = "_site"
[dev]
  command = "npm run watch"
  functions = "netlify/functions/"
  publish = "_site"
[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".cache"]
